user:
  email: 'ihn8hy@inf.elte.hu'
  password: 'TestPassw0rd123!'
  newPassword: 'TestPassw0rd321!'

protocol: "https"
domain: 'www.notebook.hu'
myAccountPrefix: 'https://www.notebook.hu/ugyfelkapu/'

search:
  product: 'apple iPhone 15 pro'
  notebook: 'ASUS ZenBook 14 OLED UM3402'

staticPagesToOpen:
  - 'fiokom'
  - 'rendeleseim'
  - 'letoltesek'
  - 'velemenyek'
#  - 'kivansaglista'
#  - 'eszamlak'

tests:
  greeting: 'Üdvözlünk, Dániel Molnár!'
  myAccountMenuItems:
    - 'Fiók áttekintő'
    - 'Személyes adatok'
    - 'Rendeléseim'
    - 'Letölthető termékek'
    - 'Termék vélemények'
    - 'Kedvenceim'
    - 'E-számlák'
    - 'Kilépés'
  mainPageMenuItems:
    - 'Fiók áttekintő'
    - 'Személyes adatok'
    - 'Kedvencek'
    - 'Rendeléseim'
    - 'Letölthető termékek'
    - 'Termék vélemények'
    - 'Kilépés'
  mainPageTitle: 'Notebook.hu :: A Laptop szakértő :: Online hitel, akár 0%THM'
  storesPageTitle: 'Üzleteink - Notebook.hu :: A Laptop szakértő :: Online hitel, akár 0%THM'
  storesPageMainTitle: 'notebook.hu üzleteink az ország 8 pontján várnak Téged!'
  successfulPwChangeMessage: 'Sikeres mentés!'
  dropDownValueName: 'Kingston SNV2S/1000G 1000 GB M.2 2280 PCIe 4.0 NVMe Belső SSD'
  dropDownValuePrice: '+ 23 742 Ft'
  alertMessage: 'Elromlott a kis laptopod? Szereld meg nálunk! HEHE'