user:
  email: 'ihn8hy@inf.elte.hu'
  password: 'TestPassw0rd123!'
  newPassword: 'TestPassw0rd321!'

protocol: "https"
domain: 'www.notebook.hu'
myAccountPrefix: 'https://www.notebook.hu/ugyfelkapu/'

search:
  product: 'apple iPhone 15 pro'

staticPagesToOpen:
  - 'fiokom'
  - 'rendeleseim'
  - 'letoltesek'
  - 'velemenyek'
#  - 'kivansaglista'
#  - 'eszamlak'

tests:
  greeting: 'Üdvözlünk, Dániel Molnár!'
  myAccountMenuItems:
    - 'Fiók áttekintő'
    - 'Személyes adatok'
    - 'Rendeléseim'
    - 'Letölthető termékek'
    - 'Termék vélemények'
    - 'Kedvenceim'
    - 'E-számlák'
    - 'Kilépés'
  mainPageMenuItems:
    - 'Fiók áttekintő'
    - 'Személyes adatok'
    - 'Kedvencek'
    - 'Rendeléseim'
    - 'Letölthető termékek'
    - 'Termék vélemények'
    - 'Kilépés'
  mainPageTitle: 'Notebook.hu :: A Laptop szakértő :: Online hitel, akár 0%THM'
  storesPageTitle: 'Üzleteink - Notebook.hu :: A Laptop szakértő :: Online hitel, akár 0%THM'
  successfullPwChangeMsg: 'Sikeres mentés!'